version: "3.9"
services:
  go_api:
    container_name: favourr-api
    build: Favourr-Api-2/
    ports:
      - 4000:4000
      - 80:80
  go_front:
    container_name: favourr-front
    build: Favourr-Front/
    ports:
      - "8080:8080"
    depends_on:
      - go_api
