version: "3.9"
services:
  favourr_golang_server:
    container_name: favourr-backend
    build: Favourr-Api-2/
    ports:
      - 4000:4000
      - 4001:80
    depends_on:
      - favourr-db
  favourr_react_native_frontend:
    container_name: favourr-frontend
    build: Favourr-Front/
      context: .
        args:
          - NODE_ENV=development
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - ./react_native_app:/opt/react_native_app/app:delegated
      - ./react_native_app/package.json:/opt/react_native_app/package.json
      - ./react_native_app/package-lock.json:/opt/react_native_app/package-lock.json
      - notused:/opt/react_native_app/app/node_modules
    depends_on:
      - favourr-backend
  favourr_postgres_database:
    container_name: favourr-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5434:5432
  favourr_hasura_graphql_engine:
    container_name: hasura-client
    image: hasura/graphql-engine:latest
    ports:
      - "8902:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:example@favourr-db:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
    depends_on:
      - favourr-db
