version: "3.9"
services:
  go_api:
    container_name: favourr_api
    build: Favourr-Api-2/
    ports:
      - 4000:4000
      - 4002:80
  go_front:
    container_name: favourr_front
    build: Favourr-Front/
    ports:
      - "8080:8080"
