version: "3.9"
services:
  go_api:
    build:
      context: .
      dockerfile: ./Favourr-Api-2/api.dockerfile
    ports:
      - 4000:4000
      - 4002:80
    volumes:
      - ./:/app
  go_front:
    container_name: app
    build:
      context: .
      dockerfile: ./Favourr-Front/front.dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "8080:8080"
